---
common:
  debug: yes
  context_uri: yes  # if false, displays the full JSON-LD context inline

solr:
  server: "http://localhost:8983/solr/muscatplus_live"

search:
  rows: 20
  page_sizes:
    - 20
    - 40
    - 100
  facet_fields:
    type:
      display_name: "Record type"
      alias: "type"
      sort: "index asc"
      display_value_map:
        person: Person
        place: Place
        institution: Institution
        source: Source
        person_person_relationship: Person to person relationship
        source_person_relationship: Source to person relationship
        source_institution_relationship: Source to institution relationship
        holding: Holding
        subject: Subject
        source_incipit: Incipit
        source_materialgroup: Source material group
    source_type_sm:
      display_name: "Source type"
      alias: "source-type"
      sort: "count desc"
    is_item_record_b:
      display_name: "Filter item records"
      alias: "item-filter"
      sort: "count desc"
      display_value_map:
        "True": "Include item records"
        "False": "Hide item records"
    key_mode_s:
      display_name: "Key or mode"
      alias: "key-mode"
      sort: "index asc"
    rism_series_sm:
      display_name: "RISM series"
      alias: "rism-series"
      sort: "index asc"
    creator_name_s:
      display_name: "Composer / Author"
      alias: "creator"
      sort: "count asc"
    institutions_sm:
      display_name: "Related institutions"
      alias: "related-institutions"
      sort: "count desc"
    holding_institution_sm:
      display_name: "Holding institution"
      alias: "holding-institution"
      sort: "index asc"
    related_people_sm:
      display_name: "Related people"
      alias: "related-people"
      sort: "count desc"
    roles_sm:
      display_name: "Roles"
      alias: "roles"
      sort: "index asc"
    qualifier_s:
      display_name: "Relationship qualifier"
      alias: "qualifier"
      sort: "count desc"
    relationship_s:
      display_name: "Relationship"
      alias: "relationship"
      sort: "index asc"