---
common:
  debug: no
  context_uri: yes  # if false, displays the full JSON-LD context inline
  secret: EvGw3ND0zB47Sp6Lk8R5M4Bh7PXmwB6x9WJVyYQx8TD72P5kM3ap39bNyEkSWFq1

solr:
  server: "http://localhost:8983/solr/muscatplus_live"

search:
  rows: 20
  page_sizes:
    - 20
    - 40
    - 100
  default_mode: "sources"
  modes:
    sources:
      display_name: "Sources"
      record_types:
        - source
      suggest_from:
        - person
    people:
      display_name: "People"
      record_types:
        - person
      suggest_from:
        - liturgical_festival
        - institution
    institutions:
      display_name: "Institutions"
      record_types:
        - institution
      suggest_from:
        - person
    festivals:
      display_name: "Liturgical Festivals"
      record_types:
        - liturgical_festival
      suggest_from:
        - person
    incipits:
      display_name: "Incipits"
      record_types:
        - incipit
  facets:
    source_type_sm: &SOURCE_TYPE
      display_name: "Source type"  # records.source_type
      alias: "source-type"
      sort: "count desc"
    is_item_record_b: &IS_ITEM_RECORD
      display_name: "Filter item records"
      alias: "item-filter"
      sort: "count desc"
      display_value_map:
        "True": "Item records only"
        "False": "Collection records only"
    key_mode_s: &KEY_MODE
      display_name: "Key or mode"  # records.key_or_mode
      alias: "key-mode"
      sort: "index asc"
    rism_series_sm: &RISM_SERIES
      display_name: "RISM series"  # records.rism_series
      alias: "rism-series"
      sort: "index asc"
    creator_name_s: &CREATOR_NAME
      display_name: "Composer / Author"  # records.composer_author
      alias: "creator"
      sort: "count desc"
    institutions_sm: &INSTITUTIONS
      display_name: "Related institutions"  # records.related_institution
      alias: "related-institutions"
      sort: "count desc"
    holding_institutions_sm: &HOLDING_INSTITUTIONS
      display_name: "Holding institution"
      alias: "holding-institution"
      sort: "index asc"
    related_people_sm: &RELATED_PEOPLE
      display_name: "Related people"
      alias: "related-people"
      sort: "count desc"
    roles_sm: &ROLES
      display_name: "Roles"
      alias: "roles"
      sort: "count desc"
    qualifier_s: &QUALIFIER
      display_name: "Relationship qualifier"
      alias: "qualifier"
      sort: "count desc"
    relationship_s: &RELATIONSHIP
      display_name: "Relationship"
      alias: "relationship"
      sort: "index asc"
    has_digitization_b: &HAS_DIGITIZATION
      display_name: "Links to digitizations"
      alias: "digitization"
      sort: "count desc"
      display_value_map:
        "True": "Only digitized sources"
        "False": "Non-digitized sources"
    liturgical_festivals_sm: &LITURGICAL_FESTIVALS
      display_name: "Liturgical festivals"
      alias: "festival"
      sort: "count desc"
    gender_s: &GENDER
      display_name: "Gender"
      alias: "gender"
      sort: "count desc"
    institution_types_sm: &INSTITUTION_TYPES
      display_name: "Institution type"
      alias: "institution-type"
      sort: "count desc"
  # Configure the filters to show when a specific type of search is being performed.
  filters:
    sources:
      source_type_sm:
        <<: *SOURCE_TYPE
      is_item_record_b:
        <<: *IS_ITEM_RECORD
      key_mode_s:
        <<: *KEY_MODE
      rism_series_sm:
        <<: *RISM_SERIES
      creator_name_s:
        <<: *CREATOR_NAME
      holding_institutions_sm:
        <<: *HOLDING_INSTITUTIONS
      has_digitization_b:
        <<: *HAS_DIGITIZATION
      liturgical_festivals_sm:
        <<: *LITURGICAL_FESTIVALS
    people:
      roles_sm:
        <<: *ROLES
      gender_s:
        <<: *GENDER
    institutions:
      roles_sm:
        <<: *ROLES
      institution_types_sm:
        <<: *INSTITUTION_TYPES
    incipits:
    festivals:

