---
common:
  debug: yes
  context_uri: yes  # if false, displays the full JSON-LD context inline
  secret: EvGw3ND0zB47Sp6Lk8R5M4Bh7PXmwB6x9WJVyYQx8TD72P5kM3ap39bNyEkSWFq1

solr:
  server: "http://localhost:8983/solr/muscatplus_live"

search:
  rows: 20
  page_sizes:
    - 20
    - 40
    - 100
  default_mode: "sources"
  modes:
    sources:
      label: "records.sources"
      record_type: "source"
    people:
      label: "records.people"
      record_type: "person"
    institutions:
      label: "records.institutions"
      record_type: "institution"
    festivals:
      label: "records.liturgical_festivals"
      record_type: "liturgical_festival"
    incipits:
      label: "records.incipits"
      record_type: "incipit"
  # Allowed values for 'type' are:
  #  - range: Creates a range facet over a set of scalar values (e.g., years).
  #  - stats: Creates a read-only facet with some interesting pre-defined stats.
  #  - toggle: Creates a simple on / off facet with a true or false value. Used only on boolean fields.
  #  - selector: Creates a facet of values for which an OR query is applied to the values.
  #  - filter: Creates a facet of values for which an AND query is applied to the values.
  #
  # Toggle facets have a field, 'active_value', which gives the value of the field when the toggle is switched 'on'.
  #  This is not always intuitive -- if we want to filter out records who have a 'true' value for a given field,
  #  then the 'active_value' must be 'false'. This is made even more confusing by the fact that toggle facets will
  #  only be active when they are given as a query parameter. So to give an example of how a query parameter might:
  #  translate to a Solr query:
  #
  #     ?fq=hide-source-contents:true  --> is_contents_record_b:false
  #     ?fq=hide-source-contents:false -> (no filter on is_contents_record_b, which is the same as is_contents_record_b:true OR false)

  facet_definitions:
    DATE_RANGE: &DATE_RANGE
      label: "records.dates"
      alias: "date-range"
      type: "range"
      field: "date_ranges_im"
      sort: "count desc"
    HIDE_SOURCE_CONTENTS: &HIDE_SOURCE_CONTENTS
      # Configures whether to show or hide Source Contents records.
      label: "Hide source contents"
      alias: "hide-source-contents"
      type: "toggle"
      field: "is_contents_record_b"
      active_value: false
      sort: "count desc"
    HIDE_SOURCE_COLLECTION_RECORDS: &HIDE_SOURCE_COLLECTION_RECORDS
      label: "Hide collection records"
      alias: "hide-source-collections"
      type: "toggle"
      field: "is_collection_record_b"
      active_value: false
      sort: "count desc"
    HIDE_SOURCE_COMPOSITE_VOLUMES: &HIDE_SOURCE_COMPOSITE_VOLUMES
      label: "Hide composite volumes"
      alias: "hide-composite-volumes"
      type: "toggle"
      field: "is_composite_volume_b"
      active_value: false
      sort: "count desc"
    SHOW_SOURCE_INCIPITS: &SHOW_SOURCE_INCIPITS
      label: "Has incipits"
      alias: "has-incipits"
      type: "toggle"
      field: "has_incipits_b"
      active_value: true
      sort: "count desc"
    SHOW_SOURCE_ARRANGEMENT: &SHOW_SOURCE_ARRANGEMENT
      label: "records.arrangement"
      alias: "is-arrangement"
      type: "toggle"
      field: "is_arrangement_b"
      active_value: true
      sort: "count desc"
    PERSON_ROLE: &PERSON_ROLE
      label: "records.role"
      alias: "person-role"
      type: "selector"
      field: "roles_sm"
      sort: "count desc"
    SOURCE_TYPE: &SOURCE_TYPE
      label: "records.source_type"
      alias: "source-type"
      type: "selector"
      field: "source_type_sm"
      sort: "count desc"
    INSTIUTION_CITY: &INSTITUTION_CITY
      label: "records.city"
      alias: "city"
      type: "filter"
      field: "city_s"
      sort: "count desc"

  # Configure the filters to show when a specific type of search is being performed.
  filters:
    sources:
      - *HIDE_SOURCE_CONTENTS
      - *HIDE_SOURCE_COLLECTION_RECORDS
      - *HIDE_SOURCE_COMPOSITE_VOLUMES
      - *DATE_RANGE
      - *SOURCE_TYPE
      - *SHOW_SOURCE_INCIPITS
      - *SHOW_SOURCE_ARRANGEMENT
    people:
      - *DATE_RANGE
      - *PERSON_ROLE
    institutions:
      - *INSTITUTION_CITY
    incipits:
    festivals:

