site_name: RISM Online
site_url: https://rism.online/docs/
nav:
  - Home: index.md
  - API:
      - "Using the API": api/api.md
      - "The Search API": api/search-api.md
      - "The Resource API": api/resource-api.md
      - "Routes": api/routes.md
      - "Search options by Mode": api/modes.md
      - "Multilingual Support": api/languages.md


theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: "blue grey"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
