[tool.poetry]
name = "search_server"
version = "0.1.0"
description = "MuscatPlus Search Server"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.13.4"
ujson = "^4.0.2"
serpy = "^0.3.1"
pyyaml = "^5.3.1"
sanic = "^21.3.4"
PyLD = "^2.0.3"
rdflib = "^5.0.0"
small-asc = {git = "https://github.com/rism-digital/small-asc.git", rev = "main"}
verovio = {git = "https://github.com/rism-digital/verovio.git", rev = "develop-features"}

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}
pytest = "^6.2.3"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
secondary = true
