[tool.poetry]
name = "search_server"
version = "0.1.0"
description = "MuscatPlus Search Server"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.11.5"
ujson = "^3.0.0"
serpy = "^0.3.1"
pysolr = "^3.9.0"
pyyaml = "^5.3.1"
sanic = "^20.6.3"
PyLD = "^2.0.3"
rdflib = "^5.0.0"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
