[tool.poetry]
name = "search_server"
version = "0.1.0"
description = "MuscatPlus Search Server"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.13.4"
ujson = "^4.0.0"
serpy = "^0.3.1"
pysolr = "^3.9.0"
pyyaml = "^5.3.1"
sanic = "^20.12.2"
PyLD = "^2.0.3"
rdflib = "^5.0.0"
verovio = {version = "^3.3.0", source = "testpypi", allow-prereleases = true}

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
secondary = true