[project]
name = "search_server"
version = "v1.0.5"
description = "MuscatPlus Search Server"
authors = [{ name = "Andrew Hankinson", email = "andrew.hankinson@rism.digital" }]
requires-python = ">=3.11,<4.0"
license = "MIT"
dependencies = [
    "pyyaml (>=6.0.1,<7.0.0)",
    "rdflib (>=7.0.0,<8.0.0)",
    "Jinja2 (>=3.1.2,<4.0.0)",
    "orjson (>=3.9.15,<4.0.0)",
    "verovio (>=5.1.0,<6.0.0)",
    "small-asc @ git+https://github.com/rism-digital/small-asc.git@main",
    "ypres @ git+https://github.com/rism-digital/ypres.git@main",
    "sanic (>=24.0.0,<26.0.0)",
    "sentry-sdk[sanic] (>=2.19.0,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
]

[dependency-groups]
dev = [
    "deptry>=0.23.0,<0.24",
    "ipython>=9.0.0,<10",
    "pytest>=8.0.0,<9",
    "pytest-cov>=6.0.0,<7",
    "aiofiles>=24.0.0,<25",
    "mypy>=1.15.0,<2",
    "pip>=25.0.1",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "PyPI"
url = "https://pypi.org/simple/"
default = true

[build-system]
requires = ['poetry-core (>=2.0,<3.0)']
build-backend = "poetry.masonry.api"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # pycodestyle warnings
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    ## Flake8 plugins
    "UP",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C",
    # flake8-django
    "DJ",
    # flake8-bandit
    "S",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

ignore = [
    # Ignore Pycodestyle line-length warnings, (mainly long comments).
    "E501",
    # Ignore McCabe complexity (for now).
    "C901",
]
