[tool.poetry]
name = "search_server"
version = "0.1.0"
description = "MuscatPlus Search Server"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.16.0"
ujson = "^5.0.0"
serpy = "^0.3.1"
pyyaml = "^6.0.0"
sanic = "^21.9.1"
PyLD = "^2.0.3"
rdflib = "^6.0.0"
small-asc = {git = "https://github.com/rism-digital/small-asc.git", rev = "main"}
verovio = {version = "^3.7.0", allow-prereleases = true}
cchardet = "2.1.7"
sentry-sdk = "^1.5.2"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}
pytest = "^6.2.3"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
secondary = true
