version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: "[%(asctime)s] [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  consoledebug:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ./logs/indexer.log
    when: D
    backupCount: 7
loggers:
  ld_export:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: NOTSET
